[package]
name = "bdds"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# peabody = { path = "../peabody" }
# cudd = { path = "../cudd-rs" }
sylvan = { path = "../sylvan-rs" }